//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.09.05 at 03:09:41 PM IST 
//


package com.sun.xml.wss.saml.internal.saml11.jaxb10.impl;

public class SignatureTypeImpl implements com.sun.xml.wss.saml.internal.saml11.jaxb10.SignatureType, com.sun.xml.bind.JAXBObject, com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.UnmarshallableObject, com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.XMLSerializable, com.sun.xml.bind.marshaller.IdentifiableObject, com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.ValidatableObject
{

    protected com.sun.xml.wss.saml.internal.saml11.jaxb10.SignedInfoType _SignedInfo;
    protected com.sun.xml.wss.saml.internal.saml11.jaxb10.KeyInfoType _KeyInfo;
    protected com.sun.xml.wss.saml.internal.saml11.jaxb10.SignatureValueType _SignatureValue;
    protected com.sun.xml.bind.util.ListImpl _Object;
    protected java.lang.String _Id;
    public final static java.lang.Class version = (com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.sun.xml.wss.saml.internal.saml11.jaxb10.SignatureType.class);
    }

    public com.sun.xml.wss.saml.internal.saml11.jaxb10.SignedInfoType getSignedInfo() {
        return _SignedInfo;
    }

    public void setSignedInfo(com.sun.xml.wss.saml.internal.saml11.jaxb10.SignedInfoType value) {
        _SignedInfo = value;
    }

    public com.sun.xml.wss.saml.internal.saml11.jaxb10.KeyInfoType getKeyInfo() {
        return _KeyInfo;
    }

    public void setKeyInfo(com.sun.xml.wss.saml.internal.saml11.jaxb10.KeyInfoType value) {
        _KeyInfo = value;
    }

    public com.sun.xml.wss.saml.internal.saml11.jaxb10.SignatureValueType getSignatureValue() {
        return _SignatureValue;
    }

    public void setSignatureValue(com.sun.xml.wss.saml.internal.saml11.jaxb10.SignatureValueType value) {
        _SignatureValue = value;
    }

    protected com.sun.xml.bind.util.ListImpl _getObject() {
        if (_Object == null) {
            _Object = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _Object;
    }

    public java.util.List getObject() {
        return _getObject();
    }

    public java.lang.String getId() {
        return _Id;
    }

    public void setId(java.lang.String value) {
        _Id = value;
    }

    public com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.UnmarshallingContext context) {
        return new com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignatureTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx4 = 0;
        final int len4 = ((_Object == null)? 0 :_Object.size());
        if (_SignedInfo instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _SignedInfo), "SignedInfo");
        } else {
            context.startElement("http://www.w3.org/2000/09/xmldsig#", "SignedInfo");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _SignedInfo), "SignedInfo");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _SignedInfo), "SignedInfo");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _SignedInfo), "SignedInfo");
            context.endElement();
        }
        if (_SignatureValue instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _SignatureValue), "SignatureValue");
        } else {
            context.startElement("http://www.w3.org/2000/09/xmldsig#", "SignatureValue");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _SignatureValue), "SignatureValue");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _SignatureValue), "SignatureValue");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _SignatureValue), "SignatureValue");
            context.endElement();
        }
        if (_KeyInfo!= null) {
            if (_KeyInfo instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _KeyInfo), "KeyInfo");
            } else {
                context.startElement("http://www.w3.org/2000/09/xmldsig#", "KeyInfo");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _KeyInfo), "KeyInfo");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _KeyInfo), "KeyInfo");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _KeyInfo), "KeyInfo");
                context.endElement();
            }
        }
        while (idx4 != len4) {
            if (_Object.get(idx4) instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Object.get(idx4 ++)), "Object");
            } else {
                context.startElement("http://www.w3.org/2000/09/xmldsig#", "Object");
                int idx_6 = idx4;
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Object.get(idx_6 ++)), "Object");
                context.endNamespaceDecls();
                int idx_7 = idx4;
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Object.get(idx_7 ++)), "Object");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Object.get(idx4 ++)), "Object");
                context.endElement();
            }
        }
    }

    public void serializeAttributes(com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx4 = 0;
        final int len4 = ((_Object == null)? 0 :_Object.size());
        if (_Id!= null) {
            context.startAttribute("", "Id");
            try {
                context.text(context.onID(this, ((java.lang.String) _Id)), "Id");
            } catch (java.lang.Exception e) {
                com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (_SignedInfo instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _SignedInfo), "SignedInfo");
        }
        if (_SignatureValue instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _SignatureValue), "SignatureValue");
        }
        if (_KeyInfo!= null) {
            if (_KeyInfo instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _KeyInfo), "KeyInfo");
            }
        }
        while (idx4 != len4) {
            if (_Object.get(idx4) instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Object.get(idx4 ++)), "Object");
            } else {
                idx4 += 1;
            }
        }
    }

    public void serializeURIs(com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx4 = 0;
        final int len4 = ((_Object == null)? 0 :_Object.size());
        if (_SignedInfo instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _SignedInfo), "SignedInfo");
        }
        if (_SignatureValue instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _SignatureValue), "SignatureValue");
        }
        if (_KeyInfo!= null) {
            if (_KeyInfo instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _KeyInfo), "KeyInfo");
            }
        }
        while (idx4 != len4) {
            if (_Object.get(idx4) instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Object.get(idx4 ++)), "Object");
            } else {
                idx4 += 1;
            }
        }
    }

    public java.lang.String ____jaxb____getId() {
        return ((java.lang.String) _Id);
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.sun.xml.wss.saml.internal.saml11.jaxb10.SignatureType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\u001dcom.sun.msv."
+"grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000\'com.sun.msv.grammar."
+"trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/gr"
+"ammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000s"
+"q\u0000~\u0000\tppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001cco"
+"m.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003sr\u0000\u0011ja"
+"va.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000 com.sun.msv.gramma"
+"r.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\fxq\u0000~\u0000\u0003q"
+"\u0000~\u0000\u0014psr\u00002com.sun.msv.grammar.Expression$AnyStringExpression\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000\u0013\u0001q\u0000~\u0000\u0018sr\u0000 com.sun.msv.grammar.AnyNameC"
+"lass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000x"
+"psr\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000\u0019q\u0000~\u0000\u001esr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/String;L\u0000\fnamespaceURIq\u0000"
+"~\u0000 xq\u0000~\u0000\u001bt\u00006com.sun.xml.wss.saml.internal.saml11.jaxb10.Sign"
+"edInfot\u0000+http://java.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000\u000bpp"
+"\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001c"
+"q\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000:com.sun.xml.wss.saml.internal.saml11.jaxb10.Si"
+"gnedInfoTypeq\u0000~\u0000#sq\u0000~\u0000\tppsq\u0000~\u0000\u0015q\u0000~\u0000\u0014psr\u0000\u001bcom.sun.msv.grammar"
+".DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000"
+"\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003pps"
+"r\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun."
+"msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv"
+".datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatyp"
+"e.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000 L\u0000\btypeNa"
+"meq\u0000~\u0000 L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceP"
+"rocessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0005QNamesr\u00005co"
+"m.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xpsr\u00000com.sun.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000\u0014psr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002"
+"L\u0000\tlocalNameq\u0000~\u0000 L\u0000\fnamespaceURIq\u0000~\u0000 xpq\u0000~\u00009q\u0000~\u00008sq\u0000~\u0000\u001ft\u0000\u0004ty"
+"pet\u0000)http://www.w3.org/2001/XMLSchema-instanceq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000\n"
+"SignedInfot\u0000\"http://www.w3.org/2000/09/xmldsig#sq\u0000~\u0000\tppsq\u0000~\u0000"
+"\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000:"
+"com.sun.xml.wss.saml.internal.saml11.jaxb10.SignatureValueq\u0000"
+"~\u0000#sq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015q\u0000~\u0000\u0014"
+"pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000>com.sun.xml.wss.saml.internal.saml1"
+"1.jaxb10.SignatureValueTypeq\u0000~\u0000#sq\u0000~\u0000\tppsq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u00001q\u0000~"
+"\u0000Aq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000\u000eSignatureValueq\u0000~\u0000Fsq\u0000~\u0000\tppsq\u0000~\u0000\tq\u0000~\u0000\u0014psq\u0000~\u0000"
+"\u000bq\u0000~\u0000\u0014p\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000"
+"\u001ft\u00003com.sun.xml.wss.saml.internal.saml11.jaxb10.KeyInfoq\u0000~\u0000#"
+"sq\u0000~\u0000\u000bq\u0000~\u0000\u0014p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015q\u0000~\u0000"
+"\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u00007com.sun.xml.wss.saml.internal.saml"
+"11.jaxb10.KeyInfoTypeq\u0000~\u0000#sq\u0000~\u0000\tppsq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u00001q\u0000~\u0000Aq\u0000~\u0000"
+"\u001esq\u0000~\u0000\u001ft\u0000\u0007KeyInfoq\u0000~\u0000Fq\u0000~\u0000\u001esq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\tq\u0000~\u0000\u0014ps"
+"q\u0000~\u0000\u000bq\u0000~\u0000\u0014p\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001es"
+"q\u0000~\u0000\u001ft\u00002com.sun.xml.wss.saml.internal.saml11.jaxb10.Objectq\u0000"
+"~\u0000#sq\u0000~\u0000\u000bq\u0000~\u0000\u0014p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015q"
+"\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u00006com.sun.xml.wss.saml.internal.s"
+"aml11.jaxb10.ObjectTypeq\u0000~\u0000#sq\u0000~\u0000\tppsq\u0000~\u0000\u0015q\u0000~\u0000\u0014pq\u0000~\u00001q\u0000~\u0000Aq\u0000"
+"~\u0000\u001esq\u0000~\u0000\u001ft\u0000\u0006Objectq\u0000~\u0000Fq\u0000~\u0000\u001esq\u0000~\u0000\tppsq\u0000~\u0000\u0015q\u0000~\u0000\u0014psq\u0000~\u0000.ppsr\u0000\u001f"
+"com.sun.msv.datatype.xsd.IDType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.da"
+"tatype.xsd.NcnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\"com.sun.msv.datatype.xsd"
+".TokenType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.datatype.xsd.StringType"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u00003q\u0000~\u00008t\u0000\u0002IDq\u0000~\u0000<\u0000q\u0000~\u0000>sq\u0000~\u0000?"
+"q\u0000~\u0000\u008bq\u0000~\u00008sq\u0000~\u0000\u001ft\u0000\u0002Idt\u0000\u0000q\u0000~\u0000\u001esr\u0000\"com.sun.msv.grammar.Express"
+"ionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/Express"
+"ionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$"
+"ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lco"
+"m/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000$\u0001pq\u0000~\u0000\u0007q\u0000~\u0000nq\u0000~\u0000\bq\u0000~\u0000"
+"%q\u0000~\u0000Oq\u0000~\u0000cq\u0000~\u0000xq\u0000~\u0000\u000fq\u0000~\u0000\'q\u0000~\u0000Iq\u0000~\u0000Qq\u0000~\u0000]q\u0000~\u0000eq\u0000~\u0000rq\u0000~\u0000\u0012q\u0000~\u0000"
+"(q\u0000~\u0000Jq\u0000~\u0000Rq\u0000~\u0000^q\u0000~\u0000fq\u0000~\u0000sq\u0000~\u0000{q\u0000~\u0000zq\u0000~\u0000oq\u0000~\u0000,q\u0000~\u0000Vq\u0000~\u0000jq\u0000~\u0000"
+"\u007fq\u0000~\u0000\u0005q\u0000~\u0000\u0083q\u0000~\u0000Zq\u0000~\u0000\nq\u0000~\u0000Gq\u0000~\u0000[q\u0000~\u0000pq\u0000~\u0000\u0006x"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.UnmarshallingContext context) {
            super(context, "----------------");
        }

        protected Unmarshaller(com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignatureTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  10 :
                        if (("Object" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _getObject().add(((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectImpl.class), 11, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("Object" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 12;
                            return ;
                        }
                        state = 11;
                        continue outer;
                    case  4 :
                        if (("SignatureValue" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _SignatureValue = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignatureValueImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignatureValueImpl.class), 7, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("SignatureValue" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 5;
                            return ;
                        }
                        break;
                    case  5 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                    case  14 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("CanonicalizationMethod" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _SignedInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignedInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignedInfoTypeImpl.class), 15, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("CanonicalizationMethod" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _SignedInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignedInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignedInfoTypeImpl.class), 15, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  3 :
                        if (("SignedInfo" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _SignedInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignedInfoImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignedInfoImpl.class), 4, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("SignedInfo" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 14;
                            return ;
                        }
                        break;
                    case  8 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("KeyName" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("KeyValue" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("RetrievalMethod" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("X509Data" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("PGPData" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("SPKIData" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("MgmtData" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (!(("" == ___uri)||("http://www.w3.org/2000/09/xmldsig#" == ___uri))) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  7 :
                        if (("KeyInfo" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoImpl.class), 10, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("KeyInfo" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 8;
                            return ;
                        }
                        state = 10;
                        continue outer;
                    case  12 :
                        attIdx = context.getAttribute("", "Encoding");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "MimeType");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (true) {
                            _getObject().add(((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl.class), 13, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        _getObject().add(((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl.class), 13, ___uri, ___local, ___qname, __atts)));
                        return ;
                    case  11 :
                        if (("Object" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _getObject().add(((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectImpl.class), 11, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("Object" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 12;
                            return ;
                        }
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 3;
                            eatText1(v);
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Id = context.addToIdTable(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  10 :
                        state = 11;
                        continue outer;
                    case  15 :
                        if (("SignedInfo" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            context.popAttributes();
                            state = 4;
                            return ;
                        }
                        break;
                    case  5 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  14 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  13 :
                        if (("Object" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            context.popAttributes();
                            state = 11;
                            return ;
                        }
                        break;
                    case  8 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromLeaveElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 9, ___uri, ___local, ___qname));
                        return ;
                    case  6 :
                        if (("SignatureValue" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            context.popAttributes();
                            state = 7;
                            return ;
                        }
                        break;
                    case  7 :
                        state = 10;
                        continue outer;
                    case  9 :
                        if (("KeyInfo" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            context.popAttributes();
                            state = 10;
                            return ;
                        }
                        break;
                    case  12 :
                        attIdx = context.getAttribute("", "Encoding");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "MimeType");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        _getObject().add(((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl) spawnChildFromLeaveElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl.class), 13, ___uri, ___local, ___qname)));
                        return ;
                    case  11 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 3;
                            eatText1(v);
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  10 :
                        state = 11;
                        continue outer;
                    case  5 :
                        if (("Id" == ___local)&&("" == ___uri)) {
                            _SignatureValue = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignatureValueTypeImpl) spawnChildFromEnterAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignatureValueTypeImpl.class), 6, ___uri, ___local, ___qname));
                            return ;
                        }
                        break;
                    case  14 :
                        if (("Id" == ___local)&&("" == ___uri)) {
                            _SignedInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignedInfoTypeImpl) spawnChildFromEnterAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignedInfoTypeImpl.class), 15, ___uri, ___local, ___qname));
                            return ;
                        }
                        break;
                    case  8 :
                        if (("Id" == ___local)&&("" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 9, ___uri, ___local, ___qname));
                            return ;
                        }
                        _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 9, ___uri, ___local, ___qname));
                        return ;
                    case  7 :
                        state = 10;
                        continue outer;
                    case  12 :
                        if (("Encoding" == ___local)&&("" == ___uri)) {
                            _getObject().add(((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl) spawnChildFromEnterAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl.class), 13, ___uri, ___local, ___qname)));
                            return ;
                        }
                        if (("Id" == ___local)&&("" == ___uri)) {
                            _getObject().add(((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl) spawnChildFromEnterAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl.class), 13, ___uri, ___local, ___qname)));
                            return ;
                        }
                        if (("MimeType" == ___local)&&("" == ___uri)) {
                            _getObject().add(((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl) spawnChildFromEnterAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl.class), 13, ___uri, ___local, ___qname)));
                            return ;
                        }
                        _getObject().add(((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl) spawnChildFromEnterAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl.class), 13, ___uri, ___local, ___qname)));
                        return ;
                    case  11 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        if (("Id" == ___local)&&("" == ___uri)) {
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  10 :
                        state = 11;
                        continue outer;
                    case  2 :
                        if (("Id" == ___local)&&("" == ___uri)) {
                            state = 3;
                            return ;
                        }
                        break;
                    case  5 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  14 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  8 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromLeaveAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 9, ___uri, ___local, ___qname));
                        return ;
                    case  7 :
                        state = 10;
                        continue outer;
                    case  12 :
                        attIdx = context.getAttribute("", "Encoding");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "MimeType");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        _getObject().add(((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl) spawnChildFromLeaveAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl.class), 13, ___uri, ___local, ___qname)));
                        return ;
                    case  11 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 3;
                            eatText1(v);
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  1 :
                            state = 2;
                            eatText1(value);
                            return ;
                        case  10 :
                            state = 11;
                            continue outer;
                        case  5 :
                            attIdx = context.getAttribute("", "Id");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            _SignatureValue = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignatureValueTypeImpl) spawnChildFromText((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SignatureValueTypeImpl.class), 6, value));
                            return ;
                        case  14 :
                            attIdx = context.getAttribute("", "Id");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                        case  8 :
                            attIdx = context.getAttribute("", "Id");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromText((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 9, value));
                            return ;
                        case  7 :
                            state = 10;
                            continue outer;
                        case  12 :
                            attIdx = context.getAttribute("", "Encoding");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "Id");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "MimeType");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            _getObject().add(((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl) spawnChildFromText((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.ObjectTypeImpl.class), 13, value)));
                            return ;
                        case  11 :
                            revertToParentFromText(value);
                            return ;
                        case  0 :
                            attIdx = context.getAttribute("", "Id");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 3;
                                eatText1(v);
                                continue outer;
                            }
                            state = 3;
                            continue outer;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
