//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.09.05 at 03:09:41 PM IST 
//


package com.sun.xml.wss.saml.internal.saml11.jaxb10.impl;

public class SubjectConfirmationTypeImpl implements com.sun.xml.wss.saml.internal.saml11.jaxb10.SubjectConfirmationType, com.sun.xml.bind.JAXBObject, com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.UnmarshallableObject, com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.XMLSerializable, com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.ValidatableObject
{

    protected com.sun.xml.wss.saml.internal.saml11.jaxb10.KeyInfoType _KeyInfo;
    protected com.sun.xml.wss.saml.internal.saml11.jaxb10.AnyType _SubjectConfirmationData;
    protected com.sun.xml.bind.util.ListImpl _ConfirmationMethod;
    public final static java.lang.Class version = (com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.sun.xml.wss.saml.internal.saml11.jaxb10.SubjectConfirmationType.class);
    }

    public com.sun.xml.wss.saml.internal.saml11.jaxb10.KeyInfoType getKeyInfo() {
        return _KeyInfo;
    }

    public void setKeyInfo(com.sun.xml.wss.saml.internal.saml11.jaxb10.KeyInfoType value) {
        _KeyInfo = value;
    }

    public com.sun.xml.wss.saml.internal.saml11.jaxb10.AnyType getSubjectConfirmationData() {
        return _SubjectConfirmationData;
    }

    public void setSubjectConfirmationData(com.sun.xml.wss.saml.internal.saml11.jaxb10.AnyType value) {
        _SubjectConfirmationData = value;
    }

    protected com.sun.xml.bind.util.ListImpl _getConfirmationMethod() {
        if (_ConfirmationMethod == null) {
            _ConfirmationMethod = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _ConfirmationMethod;
    }

    public java.util.List getConfirmationMethod() {
        return _getConfirmationMethod();
    }

    public com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.UnmarshallingContext context) {
        return new com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SubjectConfirmationTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx3 = 0;
        final int len3 = ((_ConfirmationMethod == null)? 0 :_ConfirmationMethod.size());
        while (idx3 != len3) {
            context.startElement("urn:oasis:names:tc:SAML:1.0:assertion", "ConfirmationMethod");
            int idx_0 = idx3;
            try {
                idx_0 += 1;
            } catch (java.lang.Exception e) {
                com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endNamespaceDecls();
            int idx_1 = idx3;
            try {
                idx_1 += 1;
            } catch (java.lang.Exception e) {
                com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttributes();
            try {
                context.text(((java.lang.String) _ConfirmationMethod.get(idx3 ++)), "ConfirmationMethod");
            } catch (java.lang.Exception e) {
                com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_SubjectConfirmationData!= null) {
            if (_SubjectConfirmationData instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _SubjectConfirmationData), "SubjectConfirmationData");
            } else {
                context.startElement("urn:oasis:names:tc:SAML:1.0:assertion", "SubjectConfirmationData");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _SubjectConfirmationData), "SubjectConfirmationData");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _SubjectConfirmationData), "SubjectConfirmationData");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _SubjectConfirmationData), "SubjectConfirmationData");
                context.endElement();
            }
        }
        if (_KeyInfo!= null) {
            if (_KeyInfo instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _KeyInfo), "KeyInfo");
            } else {
                context.startElement("http://www.w3.org/2000/09/xmldsig#", "KeyInfo");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _KeyInfo), "KeyInfo");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _KeyInfo), "KeyInfo");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _KeyInfo), "KeyInfo");
                context.endElement();
            }
        }
    }

    public void serializeAttributes(com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx3 = 0;
        final int len3 = ((_ConfirmationMethod == null)? 0 :_ConfirmationMethod.size());
        while (idx3 != len3) {
            try {
                idx3 += 1;
            } catch (java.lang.Exception e) {
                com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
        }
        if (_SubjectConfirmationData!= null) {
            if (_SubjectConfirmationData instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _SubjectConfirmationData), "SubjectConfirmationData");
            }
        }
        if (_KeyInfo!= null) {
            if (_KeyInfo instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _KeyInfo), "KeyInfo");
            }
        }
    }

    public void serializeURIs(com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx3 = 0;
        final int len3 = ((_ConfirmationMethod == null)? 0 :_ConfirmationMethod.size());
        while (idx3 != len3) {
            try {
                idx3 += 1;
            } catch (java.lang.Exception e) {
                com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
        }
        if (_SubjectConfirmationData!= null) {
            if (_SubjectConfirmationData instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _SubjectConfirmationData), "SubjectConfirmationData");
            }
        }
        if (_KeyInfo!= null) {
            if (_KeyInfo instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _KeyInfo), "KeyInfo");
            }
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.sun.xml.wss.saml.internal.saml11.jaxb10.SubjectConfirmationType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsr\u0000 com.sun.msv.grammar.OneOrMor"
+"eExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003ppsr\u0000\'com.sun.msv.grammar.trex.ElementPattern"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000"
+"\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclare"
+"dAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun."
+"msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/"
+"Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPai"
+"r;xq\u0000~\u0000\u0003ppsr\u0000#com.sun.msv.datatype.xsd.AnyURIType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000"
+"%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun"
+".msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000"
+"\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000\u0017L\u0000\nwhiteSpacet\u0000.Lcom/sun/"
+"msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/"
+"2001/XMLSchemat\u0000\u0006anyURIsr\u00005com.sun.msv.datatype.xsd.WhiteSpa"
+"ceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd."
+"WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expr"
+"ession$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boole"
+"an\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ej"
+"B\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0017L\u0000\fnamespaceURIq\u0000~\u0000\u0017xpq\u0000~\u0000\u001bq\u0000~\u0000\u001asr\u0000\u001d"
+"com.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com.sun."
+"msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000"
+"~\u0000\u000bxq\u0000~\u0000\u0003q\u0000~\u0000\"psq\u0000~\u0000\u000fppsr\u0000\"com.sun.msv.datatype.xsd.QnameTyp"
+"e\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0014q\u0000~\u0000\u001at\u0000\u0005QNameq\u0000~\u0000\u001eq\u0000~\u0000 sq\u0000~\u0000#q\u0000~\u0000,q\u0000~\u0000\u001asr\u0000"
+"#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq"
+"\u0000~\u0000\u0017L\u0000\fnamespaceURIq\u0000~\u0000\u0017xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-instanc"
+"esr\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000!\u0001q\u0000~\u00004sq\u0000~\u0000.t\u0000\u0012ConfirmationMethodt\u0000%urn:oasi"
+"s:names:tc:SAML:1.0:assertionsq\u0000~\u0000%ppsq\u0000~\u0000%q\u0000~\u0000\"psq\u0000~\u0000\nq\u0000~\u0000\""
+"p\u0000sq\u0000~\u0000%ppsq\u0000~\u0000\u0007q\u0000~\u0000\"psq\u0000~\u0000\'q\u0000~\u0000\"psr\u00002com.sun.msv.grammar.Ex"
+"pression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u00005q\u0000~\u0000@sr\u0000 c"
+"om.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000/q\u0000~\u00004sq\u0000~\u0000.t"
+"\u0000Ccom.sun.xml.wss.saml.internal.saml11.jaxb10.SubjectConfirm"
+"ationDatat\u0000+http://java.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000"
+"\nq\u0000~\u0000\"p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\npp\u0000sq\u0000~\u0000%ppsq\u0000~\u0000\u0007q\u0000~\u0000\"psq\u0000~\u0000\'q\u0000~\u0000\"pq\u0000~"
+"\u0000@q\u0000~\u0000Bq\u0000~\u00004sq\u0000~\u0000.t\u00003com.sun.xml.wss.saml.internal.saml11.ja"
+"xb10.AnyTypeq\u0000~\u0000Esq\u0000~\u0000%ppsq\u0000~\u0000\'q\u0000~\u0000\"pq\u0000~\u0000)q\u0000~\u00000q\u0000~\u00004sq\u0000~\u0000.t\u0000"
+"\u0017SubjectConfirmationDataq\u0000~\u00008q\u0000~\u00004sq\u0000~\u0000%ppsq\u0000~\u0000%q\u0000~\u0000\"psq\u0000~\u0000\n"
+"q\u0000~\u0000\"p\u0000sq\u0000~\u0000%ppsq\u0000~\u0000\u0007q\u0000~\u0000\"psq\u0000~\u0000\'q\u0000~\u0000\"pq\u0000~\u0000@q\u0000~\u0000Bq\u0000~\u00004sq\u0000~\u0000."
+"t\u00003com.sun.xml.wss.saml.internal.saml11.jaxb10.KeyInfoq\u0000~\u0000Es"
+"q\u0000~\u0000\nq\u0000~\u0000\"p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\npp\u0000sq\u0000~\u0000%ppsq\u0000~\u0000\u0007q\u0000~\u0000\"psq\u0000~\u0000\'q\u0000~\u0000\""
+"pq\u0000~\u0000@q\u0000~\u0000Bq\u0000~\u00004sq\u0000~\u0000.t\u00007com.sun.xml.wss.saml.internal.saml1"
+"1.jaxb10.KeyInfoTypeq\u0000~\u0000Esq\u0000~\u0000%ppsq\u0000~\u0000\'q\u0000~\u0000\"pq\u0000~\u0000)q\u0000~\u00000q\u0000~\u00004"
+"sq\u0000~\u0000.t\u0000\u0007KeyInfot\u0000\"http://www.w3.org/2000/09/xmldsig#q\u0000~\u00004sr"
+"\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000"
+"/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.su"
+"n.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000"
+"\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionPoo"
+"l;xp\u0000\u0000\u0000\u0015\u0001pq\u0000~\u0000Gq\u0000~\u0000[q\u0000~\u0000<q\u0000~\u0000Iq\u0000~\u0000Uq\u0000~\u0000]q\u0000~\u0000=q\u0000~\u0000Jq\u0000~\u0000Vq\u0000~\u0000^"
+"q\u0000~\u0000\tq\u0000~\u0000\u000eq\u0000~\u0000\u0006q\u0000~\u0000\u0005q\u0000~\u0000&q\u0000~\u0000Nq\u0000~\u0000bq\u0000~\u00009q\u0000~\u0000Rq\u0000~\u0000:q\u0000~\u0000Sx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.UnmarshallingContext context) {
            super(context, "----------");
        }

        protected Unmarshaller(com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SubjectConfirmationTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        if (("KeyInfo" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoImpl.class), 7, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("KeyInfo" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 5;
                            return ;
                        }
                        state = 7;
                        continue outer;
                    case  5 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("KeyName" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("KeyValue" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("RetrievalMethod" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("X509Data" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("PGPData" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("SPKIData" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("MgmtData" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (!(("" == ___uri)||("http://www.w3.org/2000/09/xmldsig#" == ___uri))) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  8 :
                        if (true) {
                            _SubjectConfirmationData = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.AnyTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.AnyTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _SubjectConfirmationData = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.AnyTypeImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.AnyTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  7 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  3 :
                        if (("ConfirmationMethod" == ___local)&&("urn:oasis:names:tc:SAML:1.0:assertion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        if (("SubjectConfirmationData" == ___local)&&("urn:oasis:names:tc:SAML:1.0:assertion" == ___uri)) {
                            _SubjectConfirmationData = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SubjectConfirmationDataImpl) spawnChildFromEnterElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.SubjectConfirmationDataImpl.class), 4, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("SubjectConfirmationData" == ___local)&&("urn:oasis:names:tc:SAML:1.0:assertion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 8;
                            return ;
                        }
                        state = 4;
                        continue outer;
                    case  0 :
                        if (("ConfirmationMethod" == ___local)&&("urn:oasis:names:tc:SAML:1.0:assertion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  9 :
                        if (("SubjectConfirmationData" == ___local)&&("urn:oasis:names:tc:SAML:1.0:assertion" == ___uri)) {
                            context.popAttributes();
                            state = 4;
                            return ;
                        }
                        break;
                    case  4 :
                        state = 7;
                        continue outer;
                    case  6 :
                        if (("KeyInfo" == ___local)&&("http://www.w3.org/2000/09/xmldsig#" == ___uri)) {
                            context.popAttributes();
                            state = 7;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("ConfirmationMethod" == ___local)&&("urn:oasis:names:tc:SAML:1.0:assertion" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  5 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromLeaveElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 6, ___uri, ___local, ___qname));
                        return ;
                    case  8 :
                        _SubjectConfirmationData = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.AnyTypeImpl) spawnChildFromLeaveElement((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.AnyTypeImpl.class), 9, ___uri, ___local, ___qname));
                        return ;
                    case  7 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  3 :
                        state = 4;
                        continue outer;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        state = 7;
                        continue outer;
                    case  5 :
                        if (("Id" == ___local)&&("" == ___uri)) {
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 6, ___uri, ___local, ___qname));
                            return ;
                        }
                        _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromEnterAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 6, ___uri, ___local, ___qname));
                        return ;
                    case  8 :
                        _SubjectConfirmationData = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.AnyTypeImpl) spawnChildFromEnterAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.AnyTypeImpl.class), 9, ___uri, ___local, ___qname));
                        return ;
                    case  7 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  3 :
                        state = 4;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        state = 7;
                        continue outer;
                    case  5 :
                        attIdx = context.getAttribute("", "Id");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromLeaveAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 6, ___uri, ___local, ___qname));
                        return ;
                    case  8 :
                        _SubjectConfirmationData = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.AnyTypeImpl) spawnChildFromLeaveAttribute((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.AnyTypeImpl.class), 9, ___uri, ___local, ___qname));
                        return ;
                    case  7 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  3 :
                        state = 4;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  4 :
                            state = 7;
                            continue outer;
                        case  1 :
                            state = 2;
                            eatText1(value);
                            return ;
                        case  5 :
                            attIdx = context.getAttribute("", "Id");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            _KeyInfo = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl) spawnChildFromText((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.KeyInfoTypeImpl.class), 6, value));
                            return ;
                        case  8 :
                            _SubjectConfirmationData = ((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.AnyTypeImpl) spawnChildFromText((com.sun.xml.wss.saml.internal.saml11.jaxb10.impl.AnyTypeImpl.class), 9, value));
                            return ;
                        case  7 :
                            revertToParentFromText(value);
                            return ;
                        case  3 :
                            state = 4;
                            continue outer;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _getConfirmationMethod().add(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
