
package wssc.sc_renew_1.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.8-hudson-4-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IPingService", targetNamespace = "http://xmlsoap.org/Ping")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPingService {


    /**
     * 
     * @param text
     * @param scenario
     * @param origin
     */
    @WebMethod(operationName = "Ping", action = "http://xmlsoap.org/Ping")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://xmlsoap.org/Ping", className = "wssc.sc_renew_1.client.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://xmlsoap.org/Ping", className = "wssc.sc_renew_1.client.PingResponseBody")
    public void ping(
        @WebParam(name = "scenario", targetNamespace = "http://xmlsoap.org/Ping", mode = WebParam.Mode.INOUT)
        Holder<String> scenario,
        @WebParam(name = "origin", targetNamespace = "http://xmlsoap.org/Ping", mode = WebParam.Mode.INOUT)
        Holder<String> origin,
        @WebParam(name = "text", targetNamespace = "http://xmlsoap.org/Ping", mode = WebParam.Mode.INOUT)
        Holder<String> text);

}
