/*
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the License).  You may not use this file except in
 * compliance with the License.
 *
 * You can obtain a copy of the license at
 * https://glassfish.dev.java.net/public/CDDLv1.0.html.
 * See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL
 * Header Notice in each file and include the License file
 * at https://glassfish.dev.java.net/public/CDDLv1.0.html.
 * If applicable, add the following below the CDDL Header,
 * with the fields enclosed by brackets [] replaced by
 * you own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * Copyright 2006 Sun Microsystems Inc. All Rights Reserved
 */

package com.sun.xml.ws.tx.webservice.member.coord;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_03-b18-fcs
 * Generated source version: 2.0
 */
@WebService(name = "ActivationPortTypeRPC",
        targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wscoor",
        wsdlLocation = "WEB-INF/wsdl/wscoor.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ActivationPortTypeRPC {


    /**
     * @param parameters
     * @return returns com.sun.xml.ws.tx.webservice.member.coord.CreateCoordinationContextResponseType
     */
    @WebMethod(operationName = "CreateCoordinationContextOperation", action = "http://schemas.xmlsoap.org/ws/2004/10/wscoor/CreateCoordinationContextSynch")
    @WebResult(name = "CreateCoordinationContextResponse", targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wscoor", partName = "parameters")
    @Action(input = "http://schemas.xmlsoap.org/ws/2004/10/wscoor/CreateCoordinationContext",
            output = "http://schemas.xmlsoap.org/ws/2004/10/wscoor/CreateCoordinationContextResponse")
    public CreateCoordinationContextResponseType createCoordinationContextOperation(
            @WebParam(name = "CreateCoordinationContext", targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wscoor", partName = "parameters") CreateCoordinationContextType parameters);

}
