//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.09.05 at 03:09:41 PM IST 
//


package com.sun.xml.wss.saml.internal.saml11.jaxb10;


/**
 * Java content class for MgmtData element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at http://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd line 161)
 * <p>
 * <pre>
 * &lt;element name="MgmtData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * </pre>
 * 
 */
public interface MgmtData
    extends javax.xml.bind.Element
{


    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getValue();

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setValue(java.lang.String value);

}
