//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.10 at 06:38:58 PM CET 
//


package com.sun.xml.ws.rx.mc.protocol.wsmc200702;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sun.xml.ws.rx.mc.protocol.wsmc200702 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sun.xml.ws.rx.mc.protocol.wsmc200702
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MessagePendingElement }
     * 
     */
    public MessagePendingElement createMessagePendingElement() {
        return new MessagePendingElement();
    }

    /**
     * Create an instance of {@link ExtensibleUri }
     * 
     */
    public ExtensibleUri createExtensibleUri() {
        return new ExtensibleUri();
    }

    /**
     * Create an instance of {@link UnsupportedSelectionType }
     * 
     */
    public UnsupportedSelectionType createUnsupportedSelectionType() {
        return new UnsupportedSelectionType();
    }

    /**
     * Create an instance of {@link MakeConnectionElement }
     * 
     */
    public MakeConnectionElement createMakeConnectionElement() {
        return new MakeConnectionElement();
    }

}
