
package wstrust.wssx_scenario7.sts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.8-hudson-4-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SecurityTokenService", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SecurityTokenService {


    /**
     * 
     * @param rstMessage
     * @return
     *     returns wstrust.wssx_scenario7.sts.MessageBodyType
     */
    @WebMethod(operationName = "RequestSecurityToken", action = "http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue")
    @WebResult(name = "MessageBody", targetNamespace = "http://schemas.message.com/Message", partName = "IssueTokenResult")
    public MessageBodyType requestSecurityToken(
        @WebParam(name = "MessageBody", targetNamespace = "http://schemas.message.com/Message", partName = "rstMessage")
        MessageBodyType rstMessage);

}
